projectName: MamaToto
image: jembi/platform:latest
logPath: /tmp/logs

packages:
  - reverse-proxy-nginx
  - identity-access-manager-keycloak

customPackages:
  - id: mamatoto-fhir-datastore
    path: fhir-datastore-hapi-fhir
  
  - id: mamatoto-openhim
    path: interoperability-layer-openhim

  - id: mamatoto-mediators
    path: hie

profiles:
  - name: mamatoto
    packages:
      - interoperability-layer-openhim
      - reverse-proxy-nginx
      - fhir-datastore-hapi-fhir
      - mamatoto-mediators
      - identity-access-manager-keycloak
    envFiles:
      - .env