networks:
    cloudbuild:
        external: true


services:
    matchbox:
        container_name: matchbox
        image: intellisoftkenya/matchbox:latest
        networks:
            - cloudbuild
        restart: always
        ports:
            - "8096:8080"
        # volumes:
            # - /opt/smart-hiv/matchbox/matchbox-server/with-cda:/config

