version: "3"
networks:
    openhim:
    hapi-fhir:
    mediators:
    cloudbuild:
        external: true

services:
    mongo:
        container_name: openhim-mongo
        image: mongo:4.0
        ports:
            - 27017:27017
        networks:
            - openhim
        volumes:
            - mongodb-data:/data/db
        restart: always

    client-registry-postgres:
        container_name: client-registry-postgres
        image: postgres:14-alpine
        restart: always
        networks:
            - hapi-fhir
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: hapi
            POSTGRES_PASSWORD: hapi123
        volumes:
            - 'client-registry-postgres:/var/lib/postgresql/data'
    
    shr-postgres:
        container_name: shr-postgres
        image: postgres:14-alpine
        restart: unless-stopped
        networks:
            - hapi-fhir
            - cloudbuild
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: hapi
            POSTGRES_PASSWORD: hapi123
        volumes:
            - 'shr-postgres:/var/lib/postgresql/data'

    client-registry:
        image: hapiproject/hapi:v7.4.0
        container_name: client-registry
        restart: unless-stopped
        networks:
            - hapi-fhir
            - openhim
        ports:
            - "8081:8080"
        depends_on:
            - client-registry-postgres
        volumes:
            - "./hapi-fhir:/hapi"
        environment:
            SPRING_CONFIG_LOCATION: /hapi/application.client_registry.yaml
    
    shr:
        image: hapiproject/hapi:v7.4.0
        container_name: shr
        restart: unless-stopped
        networks:
            - hapi-fhir
            - openhim
        ports:
            - "8086:8080"
        depends_on:
            - shr-postgres
        volumes:
            - "./hapi-fhir:/hapi"
        environment:
            SPRING_CONFIG_LOCATION: /hapi/application.yaml

    openhim-core:
        container_name: openhim-core
        restart: unless-stopped
        image: jembi/openhim-core:latest
        env_file:
            - .env
        ports:
            - "8080:8080"
            - "5000:5000"
            - "5001:5001"
        depends_on:
            - mongo
            - openhim-console
        networks:
            - openhim
            - hapi-fhir
            - mediators
        healthcheck:
            test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
            interval: 30s
            timeout: 30s
            retries: 3

    openhim-console:
        container_name: openhim-console
        image: jembi/openhim-console:latest
        restart: on-failure
        networks:
            - openhim
        ports:
            - "9000:80"
        healthcheck:
            test: "curl -sS http://openhim-console || exit 1"
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - ./default.json:/usr/share/nginx/html/config/default.json
            - /etc/ssl/crt:/etc/nginx/certs

    mediators:
        depends_on:
            - openhim-core
            - client-registry
            - shr
        container_name: mediators
        restart: on-failure
        build:
            context: mediators
            dockerfile: Dockerfile.dev
        volumes:
            - ./mediators:/usr/mediators
        networks:
            - openhim
            - hapi-fhir
        ports:
            - "8082:3000"
        env_file:
            - mediators/.env

    nginx:
        image: nginx:alpine
        container_name: nginx
        networks:
            - openhim
        ports:
            - "8888:80"
            - "8443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - openhim-core
    


volumes:
    mongodb-data:
    client-registry-postgres:
    hapi:
    mediators:
    shr-postgres:
