version: "3"
networks:
    openhim:
    hapi-fhir:
    mediators:
    cloudbuild:

services:

    mediators:
        # depends_on:
            # matchbox
        container_name: mediators
        restart: on-failure
        build:
            context: mediators
            dockerfile: Dockerfile.dev
        volumes:
            - ./mediators:/usr/mediators
        networks:
            - openhim
            - hapi-fhir
        ports:
            - "8082:3000"
        env_file:
            - mediators/.env

